# Generated by Django 4.2.19 on 2025-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
