# Generated by Django 4.2 on 2025-10-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('agent', 'Agent/Tennent'), ('management', 'Management'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
    ]
