# Generated by Django 5.2.6 on 2025-10-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_phone_remove_user_tenant_alter_user_role'),
    ]

    operations = [
    ]
