# Generated by Django 4.2.19 on 2025-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_updated_at_to_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bmdc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
